version: '3.8'

services:
  LoreKeeper:
    build: .
    container_name: LoreKeeper
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./public/ebooks:/app/public/ebooks
      - ./public/covers:/app/public/covers
      - ./public/books.json:/app/public/books.json